version: '2'
services:
  test:
    image: bashell/alpine-bash
    volumes:
      - ./bin/pg-copy-ch-dev:/bin/pg-copy-ch:ro
      - ./tests:/tmp/tests:ro
    working_dir: /tmp
    depends_on:
      - pg
      - ch
    environment:
      - PG_HOST=pg
      - CH_HOST=ch
  pg:
    image: postgres:9.6
  ch:
    image: yandex/clickhouse-server
